export function renderGtk2Gtkrc(flavorBlock, accentHex, accentOnHex) {
  const { surface, text, border } = flavorBlock;

  return `# Generated by tools/generate.mjs — do not edit by hand.

gtk-color-scheme = "bg_color:${surface.bg}\\nfg_color:${text.fg}\\nbase_color:${surface.bg_sunk}\\ntext_color:${text.fg}\\nselected_bg_color:${accentHex}\\nselected_fg_color:${accentOnHex}"

style "vivid-life-default" {
  bg[NORMAL]      = "${surface.bg}"
  bg[PRELIGHT]    = "${surface.bg_soft}"
  bg[ACTIVE]      = "${accentHex}"
  bg[SELECTED]    = "${accentHex}"
  bg[INSENSITIVE] = "${surface.bg_soft}"

  fg[NORMAL]      = "${text.fg}"
  fg[PRELIGHT]    = "${text.fg}"
  fg[ACTIVE]      = "${accentOnHex}"
  fg[SELECTED]    = "${accentOnHex}"
  fg[INSENSITIVE] = "${text.fg_disabled}"

  base[NORMAL]    = "${surface.bg_sunk}"
  base[SELECTED]  = "${accentHex}"

  text[NORMAL]    = "${text.fg}"
  text[SELECTED]  = "${accentOnHex}"

  xthickness = 1
  ythickness = 1
}

class "GtkWidget" style "vivid-life-default"

style "vivid-life-button" {
  bg[NORMAL]   = "${surface.bg_soft}"
  bg[PRELIGHT] = "${border.strong}"
  bg[ACTIVE]   = "${accentHex}"
  fg[ACTIVE]   = "${accentOnHex}"
}

class "GtkButton" style "vivid-life-button"

style "vivid-life-entry" {
  base[NORMAL] = "${surface.bg_sunk}"
  text[NORMAL] = "${text.fg}"
}

class "GtkEntry" style "vivid-life-entry"
`;
}
