import { buildContext } from "./context.mjs";
import * as tokens from "./gtk2/_tokens.mjs";
import * as base from "./gtk2/base.mjs";
import * as button from "./gtk2/button.mjs";
import * as entry from "./gtk2/entry.mjs";

// Cascade order is part of the contract, but it means something different
// here than in CSS. gtkrc requires a style to be defined before it is bound,
// which each module satisfies internally by emitting its style and its
// binding together. What order decides is which *binding* wins: for the same
// widget the last binding applies, and a widget_class match beats a class
// match regardless of position. _tokens first because gtk-color-scheme has
// to be set before any style references its names; base second because
// GtkWidget is the fallback every later binding narrows.
export const GTK2_MODULES = [tokens, base, button, entry];

export function renderGtk2Gtkrc(flavorBlock, accentHex, accentOnHex) {
  const ctx = buildContext(flavorBlock, accentHex, accentOnHex);
  const fragments = GTK2_MODULES.map((module) => module.render(ctx));
  return `# Generated by tools/generate.mjs — do not edit by hand.

${fragments.join("\n\n")}
`;
}
