import { buildContext } from "./context.mjs";
import * as tokens from "./gtk3/_tokens.mjs";
import * as base from "./gtk3/base.mjs";
import * as button from "./gtk3/button.mjs";
import * as entry from "./gtk3/entry.mjs";
import * as spinbutton from "./gtk3/spinbutton.mjs";
import * as scale from "./gtk3/scale.mjs";
import * as checkRadio from "./gtk3/check-radio.mjs";
import * as switchWidget from "./gtk3/switch.mjs";
import * as notebook from "./gtk3/notebook.mjs";
import * as view from "./gtk3/view.mjs";
import * as paned from "./gtk3/paned.mjs";
import * as sidebar from "./gtk3/sidebar.mjs";
import * as menu from "./gtk3/menu.mjs";
import * as headerBars from "./gtk3/header-bars.mjs";
import * as scrollbar from "./gtk3/scrollbar.mjs";
import * as progress from "./gtk3/progress.mjs";
import * as tooltip from "./gtk3/tooltip.mjs";
import * as selection from "./gtk3/selection.mjs";
import * as infobar from "./gtk3/infobar.mjs";

// Cascade order is part of the contract: _tokens first so the @define-color
// names exist before any rule references them, then base so per-widget rules
// override it. The rest is source order for its own sake — every selector
// here is specific enough to stand on its own, and the one universal-selector
// block (*:selected, zero specificity) is deliberately paired with a
// class-selector override rather than relying on where it sits.
export const GTK3_MODULES = [
  tokens,
  base,
  button,
  entry,
  spinbutton,
  scale,
  checkRadio,
  switchWidget,
  notebook,
  view,
  paned,
  sidebar,
  menu,
  headerBars,
  scrollbar,
  progress,
  tooltip,
  selection,
  infobar,
];

export function renderGtk3Css(flavorBlock, accentHex, accentOnHex) {
  const ctx = buildContext(flavorBlock, accentHex, accentOnHex);
  const fragments = GTK3_MODULES.map((module) => module.render(ctx));
  return `/* Generated by tools/generate.mjs — do not edit by hand. */

${fragments.join("\n\n")}
`;
}
