import { buildContext } from "./context.mjs";
import * as tokens from "./gtk4/_tokens.mjs";
import * as base from "./gtk4/base.mjs";
import * as button from "./gtk4/button.mjs";
import * as entry from "./gtk4/entry.mjs";
import * as checkRadio from "./gtk4/check-radio.mjs";
import * as headerBars from "./gtk4/header-bars.mjs";
import * as scrollbar from "./gtk4/scrollbar.mjs";
import * as progress from "./gtk4/progress.mjs";
import * as tooltip from "./gtk4/tooltip.mjs";
import * as menu from "./gtk4/menu.mjs";

// Cascade order is part of the contract, same as gtk3.mjs: _tokens first so
// the @define-color names exist before any rule references them, then base
// so per-widget rules override it.
export const GTK4_MODULES = [
  tokens,
  base,
  button,
  entry,
  checkRadio,
  headerBars,
  menu,
  scrollbar,
  progress,
  tooltip,
];

// GTK4's own default stylesheet is the node-name reference for this target;
// see the phase 4 plan for how to extract it. GTK3 selectors do not transfer
// unchanged — frame, expander, tooltip, popover and menubar all differ.
const HEADER = `/* Generated by tools/generate.mjs — do not edit by hand.
 *
 * GTK4 limitation: apps built on libadwaita largely ignore this
 * stylesheet and follow libadwaita's own accent-color system instead.
 * This file only affects GTK4 apps that render plain GTK4 widgets
 * without opting into libadwaita theming. See
 * docs/superpowers/specs/2026-08-30-xfce-theme-port-design.md.
 */`;

export function renderGtk4Css(flavorBlock, accentHex, accentOnHex) {
  const ctx = buildContext(flavorBlock, accentHex, accentOnHex);
  const fragments = GTK4_MODULES.map((module) => module.render(ctx));
  return `${HEADER}

${fragments.join("\n\n")}
`;
}
