export function renderGtk4Css(flavorBlock, accentHex, accentOnHex) {
  const { surface, text, border, semantic } = flavorBlock;

  return `/* Generated by tools/generate.mjs — do not edit by hand.
 *
 * GTK4 limitation: apps built on libadwaita largely ignore this
 * stylesheet and follow libadwaita's own accent-color system instead.
 * This file only affects GTK4 apps that render plain GTK4 widgets
 * without opting into libadwaita theming. See
 * docs/superpowers/specs/2026-08-30-xfce-theme-port-design.md.
 */

@define-color vl_bg ${surface.bg};
@define-color vl_bg_soft ${surface.bg_soft};
@define-color vl_bg_sunk ${surface.bg_sunk};
@define-color vl_bg_overlay ${surface.bg_overlay};
@define-color vl_fg ${text.fg};
@define-color vl_fg_muted ${text.fg_muted};
@define-color vl_fg_subtle ${text.fg_subtle};
@define-color vl_fg_disabled ${text.fg_disabled};
@define-color vl_border ${border.default};
@define-color vl_border_subtle ${border.subtle};
@define-color vl_border_strong ${border.strong};
@define-color vl_accent ${accentHex};
@define-color vl_accent_on ${accentOnHex};
@define-color vl_success ${semantic.success};
@define-color vl_warning ${semantic.warning};
@define-color vl_danger ${semantic.danger};
@define-color vl_info ${semantic.info};

window,
.background {
  background-color: @vl_bg;
  color: @vl_fg;
}

button {
  background-color: @vl_bg_soft;
  color: @vl_fg;
  border: 1px solid @vl_border;
  border-radius: 4px;
  padding: 4px 10px;
}

button:hover {
  background-color: @vl_border;
}

button:active,
button:checked {
  background-color: @vl_accent;
  color: @vl_accent_on;
}

button:disabled {
  color: @vl_fg_disabled;
}

entry {
  background-color: @vl_bg_sunk;
  color: @vl_fg;
  border: 1px solid @vl_border;
  border-radius: 4px;
  padding: 4px 6px;
}

entry:focus {
  border-color: @vl_accent;
}

check,
radio {
  background-color: @vl_bg_soft;
  border: 1px solid @vl_border;
}

check:checked,
radio:checked {
  background-color: @vl_accent;
  border-color: @vl_accent;
  color: @vl_accent_on;
}

headerbar {
  background-color: @vl_bg_soft;
  color: @vl_fg;
  border-bottom: 1px solid @vl_border;
}

scrollbar slider {
  background-color: @vl_border_strong;
  border-radius: 6px;
  min-width: 6px;
  min-height: 6px;
}

scrollbar slider:hover {
  background-color: @vl_accent;
}

progressbar > trough {
  background-color: @vl_bg_sunk;
  border-radius: 4px;
}

progressbar > trough > progress {
  background-color: @vl_accent;
  border-radius: 4px;
}

tooltip {
  background-color: @vl_bg_overlay;
  color: @vl_fg;
  border: 1px solid @vl_border;
}
`;
}
