import { themeDirName } from "../lib/paths.mjs";

const titleCase = (word) => word[0].toUpperCase() + word.slice(1);

export function renderIndexTheme(flavor, variant, flavorBlock) {
  const dir = themeDirName(flavor, variant);
  const iconTheme =
    flavorBlock.type === "dark" ? "Papirus-Dark" : "Papirus-Light";

  return `# Generated by tools/generate.mjs — do not edit by hand.
[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Vivid Life ${titleCase(flavor)} ${titleCase(variant)}
Comment=Vivid Life Theme — ${titleCase(flavor)} flavor, ${titleCase(variant)} variant
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=${dir}
MetacityTheme=${dir}
IconTheme=${iconTheme}
`;
}
