export function renderThemerc(flavorBlock, accentHex, accentOnHex) {
  const { text } = flavorBlock;

  // Drop-shadow values map from the design system's shadows.lg,
  // "0 12px 32px rgba(0,0,0,0.18)": the 12px y-offset becomes
  // shadow_delta_y, the 0.18 alpha becomes shadow_opacity.
  return `# Generated by tools/generate.mjs — do not edit by hand.
active_text_color=${text.fg}
inactive_text_color=${text.fg_muted}
title_shadow_active=false
title_shadow_inactive=false
title_alignment=left
title_horizontal_offset=12
title_vertical_offset_active=0
title_vertical_offset_inactive=0
full_width_title=true
button_offset=4
button_spacing=2
maximized_offset=0
show_app_icon=false
show_frame_shadow=true
show_popup_shadow=true
shadow_delta_x=0
shadow_delta_y=-12
shadow_delta_width=0
shadow_delta_height=2
shadow_opacity=18
`;
}

export const BUTTON_KINDS = ["close", "hide", "maximize"];

const GLYPHS = {
  close: "M4,4 L12,12 M12,4 L4,12",
  hide: "M4,11 L12,11",
  maximize: "M4,4 L12,4 L12,12 L4,12 Z",
};

export function renderButtonSvg({ kind, active, backgroundHex, glyphHex }) {
  const glyphPath = GLYPHS[kind];
  if (!glyphPath) {
    throw new Error(`Unknown button kind: ${kind}`);
  }
  const opacity = active ? "1" : "0.5";

  return `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <circle cx="8" cy="8" r="7" fill="${backgroundHex}" opacity="${opacity}" />
  <path d="${glyphPath}" stroke="${glyphHex}" stroke-width="1.5" stroke-linecap="round" fill="none" opacity="${opacity}" />
</svg>
`;
}
