export function renderThemerc(flavorBlock, accentHex, accentOnHex) {
  const { text, border } = flavorBlock;

  return `# Generated by tools/generate.mjs — do not edit by hand.
active_text_color=${text.fg}
inactive_text_color=${text.fg_subtle}
active_shadow_color=${border.strong}
inactive_shadow_color=${border.subtle}
button_offset=0
title_alignment=left
title_shadow_active=false
title_shadow_inactive=false
show_app_icon=1
full_width_title=true
`;
}

export const BUTTON_KINDS = ["close", "hide", "maximize"];

const GLYPHS = {
  close: "M4,4 L12,12 M12,4 L4,12",
  hide: "M4,11 L12,11",
  maximize: "M4,4 L12,4 L12,12 L4,12 Z",
};

export function renderButtonSvg({ kind, active, backgroundHex, glyphHex }) {
  const glyphPath = GLYPHS[kind];
  if (!glyphPath) {
    throw new Error(`Unknown button kind: ${kind}`);
  }
  const opacity = active ? "1" : "0.5";

  return `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <circle cx="8" cy="8" r="7" fill="${backgroundHex}" opacity="${opacity}" />
  <path d="${glyphPath}" stroke="${glyphHex}" stroke-width="1.5" stroke-linecap="round" fill="none" opacity="${opacity}" />
</svg>
`;
}
